baseURL = 'https://florenp.github.io/'
defaultContentLanguage = 'fr'
title = 'AFBC'
theme = "loveit"

[params]
  [params.header]
    [params.header.title]
        name = "AFBC"
  [params.home]
    [params.home.profile]
        subtitle = "Ateliers AFBC"
  [params.footer]
    enable = false

[menus]
  [[menus.main]]
    name = 'u7'
    pageRef = '/categories/u7'
    weight = 10
  [[menus.main]]
    name = 'u9'
    pageRef = '/categories/u9'
    weight = 20
  [[menus.main]]
    name = 'u11'
    pageRef = '/categories/u11'
    weight = 30
  [[menus.main]]
    name = 'u13'
    pageRef = '/categories/u13'
    weight = 40
