baseURL = 'https://florenp.github.io/'
languageCode = 'en-us'
title = 'AFBC'
theme = "loveit"

[params]
  [params.header]
    [params.header.title]
        name = "AFBC"
  [params.home]
    [params.home.profile]
        subtitle = "Ateliers AFBC"
  [params.footer]
    enable = false

[[menu.shortcuts]]
name = "<i class='fas fa-tags'></i> Tags"
url = "/tags"
weight = 30